### ISSUE TITLE
Labels in epub-spec repo

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-wg#12]
Ivan has mentioned having better documentation for the 87 labels in the spec repository. 

1. Many of the labels do not have a description. We can work on adding descriptions.

2. OK to remove labels that have never been used? One example: Vocab-Magazine 

3. It would be nice to have a label for editorial issues--issues that do not affect conformance or change the meaning of the spec.

**Comment by mattgarrish** [comment]
We've accumulated more labels than will ever be used (google code added some, github added more, w3c even more). I rarely bother with most of them. The only really helpful ones for editing are the "Spec-*" for grouping issues by where in the spec they are.

There are a couple of categories that are useful, but these are often redundant to the Spec- labels.

The priority labels are generally useless.

The Type labels are generally useless.

> OK to remove labels that have never been used?

Just be careful about the "Spec-*" ones and the "EPUB3*" labels. We've used those to link from the change documents/logs to the completed issues for a revision.

> It would be nice to have a label for editorial issues--issues that do not affect conformance or change the meaning of the spec.

Why not have two! Type-Typo and Type-Editorial :)

**Comment by mattgarrish** [comment]
> > OK to remove labels that have never been used?
> 
> Just be careful about the "Spec-" ones and the "EPUB3X" labels.

To clarify, just because github says there aren't any open issues doesn't mean the label isn't useful for closed issues...

**Comment by iherman** [comment]
Long time gone and label usages are now in place...
