### ISSUE TITLE
Update to new Patent Policy

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-wg#13]
We [discussed moving to the new patent policy](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-12-epub#section3) during yesterday's meeting. Florian was very hepful in explaining the differences. Given that the EPUB 3 WG works on multiple specs, and will likely be maintaining specs into the future, the consensus of the meeting was to move to the new patent policy.

**Comment by iherman** [comment]
long outdated...
